export const projectConfig = {
  type: "page",
  label: "页面配置",
  configureValue: {
    pageConfigWidth: 1366,
    pageConfigHeight: 768,
    horizontalNumber: 4,
    verticalNumber: 3,
    styleBackgroundColor: "#090548",
    headerStyleHeight: 80,
    headerShow: true,
  },
  configure: [
    [
      {
        name: "基础设置",
        list: [
          {
            componentName: "InputNumber",
            label: "宽度",
            name: "pageConfigWidth",
            required: false,
            min: 1366,
            max: 5000,
            tooltip: "只有配置页面有用，预览页面是全屏",
            placeholder: "请输入宽度",
          },
          {
            componentName: "InputNumber",
            label: "高度",
            name: "pageConfigHeight",
            required: false,
            min: 768,
            max: 3000,
            tooltip: "只有配置页面有用，预览页面是全屏",
            placeholder: "请输入高度",
          },
          {
            componentName: "InputNumber",
            label: "横几屏",
            name: "horizontalNumber",
            required: false,
            min: 1,
            max: 6,
            placeholder: "请输入横几屏",
          },
          {
            componentName: "InputNumber",
            label: "竖几屏",
            min: 1,
            max: 6,
            name: "verticalNumber",
            required: false,
            placeholder: "请输入竖几屏",
          },
          {
            componentName: "SketchPicker",
            label: "背景颜色",
            name: "styleBackgroundColor",
            required: false,
            placeholder: "请选择背景颜色",
          },
          {
            componentName: "Input",
            label: "背景图片",
            name: "styleBackgroundImage",
            required: false,
            placeholder: "请输入背景图片地址",
          },
        ],
      },
    ],
    [
      {
        name: "头部",
        list: [
          {
            componentName: "Switch",
            label: "是否显示",
            name: "headerShow",
            required: false,
            placeholder: "",
          },
          {
            componentName: "Input",
            label: "背景图",
            name: "headerStyleBackgroundImage",
            required: false,
            placeholder: "请输入背景图地址",
          },
          {
            componentName: "SketchPicker",
            label: "背景颜色",
            name: "headerStyleBackgroundColor",
            required: false,
            placeholder: "",
          },
          {
            componentName: "InputNumber",
            label: "高度",
            name: "headerStyleHeight",
            required: false,
            placeholder: "请输入高度",
            addonAfter: "px",
          },
        ],
      },
      {
        name: "主体",
        list: [
          {
            componentName: "Input",
            label: "背景图",
            name: "bodyStyleBackgroundImage",
            required: false,
            placeholder: "请输入背景图地址",
          },
          {
            componentName: "SketchPicker",
            label: "背景颜色",
            name: "bodyStyleBackgroundColor",
            required: false,
            placeholder: "",
          },
        ],
      },
      {
        name: "辅助线",
        list: [
          {
            componentName: "SketchPicker",
            label: "边框颜色",
            name: "auxiliaryLineBorderColor",
            required: false,
            placeholder: "",
          },
        ],
      },
    ],
    [
      {
        name: "微件配置",
        list: [
          {
            componentName: "Input",
            label: "背景图",
            name: "widgetStyleBackgroundImage",
            required: false,
            placeholder: "请输入背景图地址",
          },
          {
            componentName: "SketchPicker",
            label: "背景颜色",
            name: "widgetStyleBackgroundColor",
            required: false,
            placeholder: "",
          },
          [
            {
              name: "盒子阴影",
              list: [
                {
                  componentName: "Switch",
                  label: "内阴影",
                  name: "widgetStyleBoxInset",
                  required: false,
                  placeholder: "",
                },
                {
                  componentName: "InputNumber",
                  label: "X轴偏移",
                  name: "widgetStyleBoxShadowX",
                  required: false,
                  placeholder: "请输入X轴偏移",
                  addonAfter: "px",
                },
                {
                  componentName: "InputNumber",
                  label: "Y轴偏移",
                  name: "widgetStyleBoxShadowY",
                  required: false,
                  placeholder: "请输入Y轴偏移",
                  addonAfter: "px",
                },
                {
                  componentName: "InputNumber",
                  label: "模糊值",
                  name: "widgetStyleBoxShadowF",
                  required: false,
                  placeholder: "请输入模糊值",
                  addonAfter: "px",
                },
                {
                  componentName: "SketchPicker",
                  label: "颜色",
                  name: "widgetStyleBoxShadowC",
                  required: false,
                  placeholder: "请选择颜色",
                },
              ],
            },
            {
              name: "边框",
              list: [
                {
                  componentName: "Select",
                  label: "边框样式",
                  name: "widgetStyleBorderStyle",
                  required: false,
                  placeholder: "请选择边框样式",
                  options: [
                    { code: "none", name: "无" },
                    { code: "solid", name: "直线" },
                    { code: "dashed", name: "破折线" },
                    { code: "dotted", name: "点状线" },
                    { code: "double", name: "双划线" },
                    { code: "groove", name: "3D凹槽" },
                    { code: "ridge", name: "3D垄状" },
                    { code: "inset", name: "3D内嵌" },
                    { code: "outset", name: "3D外嵌" },
                  ],
                },
                {
                  componentName: "InputNumber",
                  label: "边框尺寸",
                  name: "widgetStyleBorderWidth",
                  required: false,
                  placeholder: "请输入尺寸",
                  addonAfter: "px",
                },
                {
                  componentName: "SketchPicker",
                  label: "颜色",
                  name: "widgetStyleBorderColor",
                  required: false,
                  placeholder: "请选择边框颜色",
                },
              ],
            },
            {
              name: "圆角",
              list: [
                {
                  componentName: "InputNumber",
                  label: "左上",
                  name: "widgetStyleBorderTopLeftRadius",
                  required: false,
                  placeholder: "请输入尺寸",
                  addonAfter: "px",
                },
                {
                  componentName: "InputNumber",
                  label: "右上",
                  name: "widgetStyleBorderTopRightRadius",
                  required: false,
                  placeholder: "请输入尺寸",
                  addonAfter: "px",
                },
                {
                  componentName: "InputNumber",
                  label: "左下",
                  name: "widgetStyleBorderBottomLeftRadius",
                  required: false,
                  placeholder: "请输入尺寸",
                  addonAfter: "px",
                },
                {
                  componentName: "InputNumber",
                  label: "右下",
                  name: "widgetStyleBorderBottomRightRadius",
                  required: false,
                  placeholder: "请输入尺寸",
                  addonAfter: "px",
                },
              ],
            },
          ],
          [
            {
              name: "头部",
              list: [
                {
                  componentName: "Input",
                  label: "背景图",
                  name: "widgetHeaderStyleBackgroundImage",
                  required: false,
                  placeholder: "请输入背景图地址",
                },
                {
                  componentName: "SketchPicker",
                  label: "背景颜色",
                  name: "widgetHeaderStyleBackgroundColor",
                  required: false,
                  placeholder: "",
                },
                {
                  componentName: "InputNumber",
                  label: "高度",
                  name: "widgetHeaderStyleHeight",
                  required: false,
                  placeholder: "请输入高度",
                  addonAfter: "px",
                },
                {
                  componentName: "SketchPicker",
                  label: "下边框颜色",
                  name: "widgetHeaderStyleBorderBottomColor",
                  required: false,
                  placeholder: "",
                },
              ],
            },
            {
              name: "主体",
              list: [
                {
                  componentName: "Input",
                  label: "背景图",
                  name: "widgetBodyStyleBackgroundImage",
                  required: false,
                  placeholder: "请输入背景图地址",
                },
                {
                  componentName: "SketchPicker",
                  label: "背景颜色",
                  name: "widgetBodyStyleBackgroundColor",
                  required: false,
                  placeholder: "",
                },
              ],
            },
          ],
        ],
      },
    ],
  ],
};
